name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}-tests

permissions:
  contents: read

env:
  IDP_CLIENT_CREDENTIAL: ${{ secrets.IDP_CLIENT_CREDENTIAL }}
  IDP_CLIENT_ID: ${{ secrets.IDP_CLIENT_ID }}
  IDP_AUTHORITY: ${{ secrets.IDP_AUTHORITY }}

jobs:
  tests:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', 'pypy-3.9', 'pypy-3.10']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev_requirements.txt

    - name: Run tests with Python version ${{ matrix.python-version }}
      run: |
        pytest --junitxml=test-results.xml

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.xml